---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Leer hoe je een hoogste score kunt bijhouden voor je Scratch-spel
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Stap een
