title: generic-scratch3-high-score
hero_image: images/banner.png
description: generic-scratch3-high-score description
version: 4
listed: false
copyedit: false
last_tested: "2018-10-19"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
