---
title: Scratch मध्ये उच्च स्कोअर तयार करा
hero_image: प्रतिमा / banner.png
description: आपल्या Scratch खेळासाठी उच्च स्कोअर कसा तयार करावा ते शिका
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: पहिली पाऊल
