---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Узнай, как создать переменную для хранения информации о лучшем результате твоей игры на Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Шаг 1
