---
title: स्क्रैच में हाई स्कोर बनाएं
hero_image: images/banner.png
description: अपने स्क्रैच खेल के लिए हाई स्कोर बनाना सीखें
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: पहला कदम
