---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Научите како да направите најбољи резултат за вашу Скреч игру
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Први корак
