---
title: Lag en toppscore i Scratch
hero_image: images/banner.png
description: Lær hvordan du lager en toppscore for Scratch-spillet ditt
listed: false
copyedit: true
site_areas:
steps:
  - title: Steg en
