---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Lær, hvordan du laver en high score for dit Scratch-spil
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Trin et
