---
title: Criar uma "Melhor pontuação" no Scratch
hero_image: images/banner.png
description: Aprende a criar a "Melhor pontuação" para o teu jogo Scratch
listed: false
copyedit: true
site_areas:
steps:
  - title: Primeiro passo
