---
title: Създайте висок резултат в Scratch
hero_image: images/banner.png
description: Научете как да постигнете висок резултат във вашата игра Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Първа стъпка
