---
title: Dodaj najbolji rezultat u Scratchu
hero_image: images/banner.png
description: Nauči kako dodati najbolji rezultat svojoj igri u Scratchu
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Prvi korak
