---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Saznaj kako spremiti najbolji rezultat u Scratch igri
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Prvi korak
