---
title: Luo korkein pistemäärä Scratchissä
hero_image: images/banner.png
description: Opi luomaan korkein pistemäärä Scratch-pelillesi
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Ensimmäinen askel
