---
title: Lumikha ng mataas na marka sa Scratch
hero_image: images/banner.png
description: Matuto kung paano lumikha ng isang mataas na marka sa ginawa mong laro sa Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Unang hakbang
