---
title: Create a high score in Scratch
hero_image: images / banner.png
description: Aprende a crear una puntuación máxima para tu juego en Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Paso uno
