---
title: Create a high score in Scratch
hero_image: images/banner.png
description: So erstellst du einen höchsten Punkstand für dein Scratch-Spiel
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Schritt eins
