---
title: Einen Highscore in Scratch erstellen
hero_image: images/banner.png
description: So erstellst du einen Highscore (höchsten Punktestand) für dein Scratch-Spiel
listed: false
copyedit: true
site_areas:
steps:
  - title: Schritt eins
