---
title: Salvează cel mai mare scor în Scratch
hero_image: images/banner.png
description: Învață cum să salvezi cel mai mare scor în jocul tău Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Pasul unu
