---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Învățați cum să creați un clasament pentru jocul Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Pasul unu
