---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Aprenda a criar o registo de pontuação máxima para o seu jogo no Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Primeiro passo
