---
title: Crie uma pontuação mais alta no Scratch
hero_image: images/banner.png
description: Aprenda como criar uma pontuação mais alta para o seu jogo no Scratch
listed: false
copyedit: true
site_areas:
steps:
  - title: Primeiro passo
