---
title: Buat daftar skor tertinggi di Scratch
hero_image: images/banner.png
description: Pelajari cara membuat skor tertinggi untuk permainan Scratch kamu
listed: false
copyedit: true
site_areas:
steps:
  - title: Langkah pertama
