---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Pelajari cara membuat skor tertinggi untuk permainan Scratch Kamu
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Langkah pertama
