---
title: Crea una puntuació alta a Scratch
hero_image: images/banner.png
description: Aprèn a crear una puntuació alta per al teu joc de Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Pas 1
