---
title: Izmeri najboljši rezultat v Scratchu
hero_image: images / banner.png
description: Nauči se, kako izmeriti najboljši rezultat za igro v Scratchu
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Prvi korak
