---
title: Sledování nejvyššího skóre ve Scratchi
hero_image: images/banner.png
description: Nauč se sledovat nejvyšší skóre ve své hře ve Scratchi
listed: false
copyedit: true
site_areas:
steps:
  - title: První krok
