---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Learn how to create a high score for your Scratch game
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Step one
