---
title: Hozz létre rekord pontszámot a Scratchben
hero_image: images/banner.png
description: Tanuld meg, hogyan lehet rekord pontszámot létrehozni a Scratch játékodhoz
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Első lépés
