---
title: Crea una puntuaci칩n m치xima en Scratch
hero_image: images/banner.png
description: Aprende a crear una puntuaci칩n m치xima para tu juego Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Primer paso
