---
title: Loo Scratchis suur skoor
hero_image: images/banner.png
description: Õpi oma Scratchi mängu jaoks suure skoori loomist
listed: false
copyedit: true
site_areas:
steps:
  - title: Esimene samm
