---
title: Create a high score in Scratch
hero_image: images/banner.png
description: Dowiedz się, jak stworzyć w Scratchu najlepszy wynik w grze
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Krok pierwszy
