---
title: Utwórz tabelę wyników w Scratch
hero_image: images/banner.png
description: Dowiedz się, jak stworzyć w Scratchu tabelę najlepszych wyników w grze
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Krok pierwszy
