---
title: Vytvorenie vysokého skóre v jazyku Scratch
hero_image: images / banner.png
description: Naučíte sa ako vytvoriť vysoké skóre pre hru v jazyku Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Prvý krok
