---
title: Créer un meilleur score dans Scratch
hero_image: images/banner.png
description: Apprends comment créer un meilleur score pour ton jeu Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Première étape
