---
title: Creare un record in Scratch
hero_image: images/banner.png
description: Scopri come creare un punteggio record per il tuo gioco di Scratch
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Primo step
