---
title: Scratch'ta yüksek skor oluşturun
hero_image: images / banner.png
description: Scratch oyununuz için nasıl yüksek skor oluşturulacağını öğrenin
listed: false
copyedit: true
site_areas:
steps:
  - 
    title: Birinci adım
